name: Setup
description: Default setup action

runs:
  using: "composite"
  steps:
    
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash
