name: Publish

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          repository: self-assert/self-assert

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run docs:build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Debug
        run: |
          ls ./packages/docs/site/.vitepress/dist
        env:
          GITHUB_CONTEXT: ${{ toJson(steps.pages.outputs) }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/docs/site/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
