name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

  build-self-assert-docs:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Generate package docs
        run: |
          ls
          npm run update:self-assert

  build:
    needs: build-self-assert-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate docs
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
